TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devKeithley6487.db
DB_INSTALLS += $(TOP)/Keithley6487Sup/devKeithley6487.proto

#=======================================
include $(TOP)/configure/RULES
